### ISSUE TITLE
Correct links to regedit

### ISSUE THREAD

**Issue by Jakub-Urban** [MicrosoftDocs/Azure-RMSDocs.cs-cz#17]
There is no HKEY_CURRENT-USER but HKEY_CURRENT_USER
[Sem napište váš názor.]

---
#### Podrobnosti dokumentu

⚠ *Neupravujte tuto část. Vyžaduje se k propojení problémů docs.microsoft.com ➟ GitHub.*

* ID: be1e1c46-7da6-6abd-cf7e-508932b7f217
* Version Independent ID: c5d25e69-4b80-a517-e0b0-79e79a5a9dc1
* Content: [Příručka pro správce klienta služby Azure Information Protection](https://docs.microsoft.com/cs-cz/azure/information-protection/rms-client/client-admin-guide#feedback)
* Content Source: [Azure-RMSDocs/rms-client/client-admin-guide.md](https://github.com/MicrosoftDocs/Azure-RMSDocs.cs-cz/blob/live/Azure-RMSDocs/rms-client/client-admin-guide.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by CeciAc** [comment]
Hello, @Jakub-Urban 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/Azure-RMSDocs/issues/922

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
